# AI-Powered Financial Fraud Detection & Risk Analytics System

## Notebook 2: Data Preprocessing & Feature Engineering

### Objective

The objective of this notebook is to prepare the transaction dataset for machine learning by creating meaningful features, transforming raw attributes into analytical variables, and generating a model-ready dataset for fraud detection.

### Key Tasks

- Create transaction time features
- Create balance error features
- Generate customer and merchant attributes
- Create synthetic banking features
- Create behavioral and demographic attributes
- Prepare processed dataset for model training

### Input

../data/raw/paysim.csv

### Output

../data/processed/fraud_processed.csv

In [29]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/paysim.csv")

print(f"Dataset Shape: {df.shape}")

fraud_df = df.copy()

fraud_df.head()

Dataset Shape: (6362620, 11)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [30]:
# Transaction Time Features

fraud_df["transaction_hour"] = fraud_df["step"] % 24

fraud_df["transaction_day"] = (
    fraud_df["step"] // 24
) + 1

fraud_df["transaction_week"] = (
    fraud_df["transaction_day"] // 7
) + 1

fraud_df[
    [
        "step",
        "transaction_hour",
        "transaction_day",
        "transaction_week"
    ]
].head()

   step  transaction_hour  transaction_day  transaction_week
0     1                 1                1                 1
1     1                 1                1                 1
2     1                 1                1                 1
3     1                 1                1                 1
4     1                 1                1                 1

In [31]:
# Balance Error Features

fraud_df["balance_error_org"] = (
    fraud_df["oldbalanceOrg"]
    - fraud_df["newbalanceOrig"]
    - fraud_df["amount"]
)

fraud_df["balance_error_dest"] = (
    fraud_df["newbalanceDest"]
    - fraud_df["oldbalanceDest"]
    - fraud_df["amount"]
)

fraud_df[
    [
        "balance_error_org",
        "balance_error_dest"
    ]
].head()

   balance_error_org  balance_error_dest
0       1.455192e-11            -9839.64
1      -1.136868e-12            -1864.28
2       0.000000e+00             -181.00
3       0.000000e+00           -21363.00
4       0.000000e+00           -11668.14

In [32]:
# Customer and Merchant Categories

fraud_df["customer_type"] = (
    fraud_df["nameOrig"].str[0]
)

fraud_df["merchant_type"] = (
    fraud_df["nameDest"].str[0]
)

fraud_df[
    [
        "customer_type",
        "merchant_type"
    ]
].head()

  customer_type merchant_type
0             C             M
1             C             M
2             C             C
3             C             C
4             C             M

In [33]:
# Age Group Feature

np.random.seed(42)

fraud_df["age_group"] = np.random.choice(
    [
        "18-25",
        "26-35",
        "36-45",
        "46-60",
        "60+"
    ],
    size=len(fraud_df),
    p=[
        0.20,
        0.35,
        0.25,
        0.15,
        0.05
    ]
)

fraud_df["age_group"].value_counts()

age_group
26-35    2226557
36-45    1591818
18-25    1272479
46-60     953551
60+       318215
Name: count, dtype: int64

In [34]:
# Customer Segment Feature

fraud_df["customer_segment"] = np.random.choice(
    [
        "Retail",
        "Premium",
        "Business"
    ],
    size=len(fraud_df),
    p=[
        0.70,
        0.20,
        0.10
    ]
)

fraud_df["customer_segment"].value_counts()

customer_segment
Retail      4453569
Premium     1273058
Business     635993
Name: count, dtype: int64

In [35]:
# Banking Channel Feature

fraud_df["channel"] = np.random.choice(
    [
        "Mobile App",
        "Internet Banking",
        "ATM",
        "Branch"
    ],
    size=len(fraud_df),
    p=[
        0.50,
        0.25,
        0.15,
        0.10
    ]
)

fraud_df["channel"].value_counts()

channel
Mobile App          3179608
Internet Banking    1592024
ATM                  954654
Branch               636334
Name: count, dtype: int64

In [36]:
# Device Type Feature

fraud_df["device_type"] = np.random.choice(
    [
        "Android",
        "iPhone",
        "Desktop",
        "Tablet"
    ],
    size=len(fraud_df),
    p=[
        0.45,
        0.25,
        0.20,
        0.10
    ]
)

fraud_df["device_type"].value_counts()

device_type
Android    2861352
iPhone     1591087
Desktop    1273214
Tablet      636967
Name: count, dtype: int64

In [37]:
# Region Feature

fraud_df["risk_region"] = np.random.choice(
    [
        "North",
        "South",
        "East",
        "West",
        "Central"
    ],
    size=len(fraud_df)
)

fraud_df["risk_region"].value_counts()

risk_region
West       1273304
North      1272748
Central    1272675
East       1272037
South      1271856
Name: count, dtype: int64

In [38]:
# Account Tenure Feature

fraud_df["account_tenure_months"] = np.random.randint(
    1,
    120,
    size=len(fraud_df)
)

fraud_df["account_tenure_months"].describe()

count    6.362620e+06
mean     6.000054e+01
std      3.434668e+01
min      1.000000e+00
25%      3.000000e+01
50%      6.000000e+01
75%      9.000000e+01
max      1.190000e+02
Name: account_tenure_months, dtype: float64

In [39]:
print(f"Final Dataset Shape: {fraud_df.shape}")

fraud_df.head()

Final Dataset Shape: (6362620, 24)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,...,balance_error_org,balance_error_dest,customer_type,merchant_type,age_group,customer_segment,channel,device_type,risk_region,account_tenure_months
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,...,1.455192e-11,-9839.64,C,M,26-35,Retail,Mobile App,iPhone,Central,20
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,...,-1.136868e-12,-1864.28,C,M,60+,Retail,Internet Banking,Android,East,7
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,...,0.000000e+00,-181.00,C,C,36-45,Retail,Internet Banking,Desktop,East,39
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,...,0.000000e+00,-21363.00,C,C,36-45,Premium,Mobile App,Android,North,116
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,...,0.000000e+00,-11668.14,C,M,18-25,Retail,Internet Banking,iPhone,East,19

In [40]:
fraud_df.to_csv(
    "../data/processed/fraud_processed.csv",
    index=False
)

print("Processed Dataset Saved Successfully")

Processed Dataset Saved Successfully

In [41]:
fraud_df["isFraud"].value_counts()

isFraud
0    6354407
1       8213
Name: count, dtype: int64

## Conclusion

Feature engineering has been completed successfully. The dataset now contains transaction, behavioral, customer, channel, device, and risk-related attributes that will support fraud detection model development.

The processed dataset will be used in the next notebook for machine learning model training and evaluation.