In [59]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [60]:
df = pd.read_csv(
    "../data/processed/fraud_risk_scored.csv"
)

print(df.shape)

(6362620, 33)

In [61]:
total_transactions = len(df)

print(total_transactions)

6362620

In [62]:
total_frauds = df["isFraud"].sum()

print(total_frauds)

8213

In [63]:
fraud_rate = (
    total_frauds /
    total_transactions
) * 100

print(round(fraud_rate,4))

0.1291

In [64]:
total_amount = df["amount"].sum()

print(total_amount)

1144392944759.77

In [65]:
avg_amount = df["amount"].mean()

print(avg_amount)

179861.90354913071

In [66]:
critical_alerts = (
    df["risk_category"] == "Critical"
).sum()

print(critical_alerts)

7352

In [67]:
high_risk = (
    df["risk_category"] == "High"
).sum()

print(high_risk)

732

In [68]:
investigation_required = (
    df["investigation_required"] == "Yes"
).sum()

print(investigation_required)

8084

In [69]:
review_required = (
    df["review_required"] == "Yes"
).sum()

print(review_required)

8193

In [70]:
executive_kpis = pd.DataFrame({

    "KPI": [

        "Total Transactions",
        "Fraud Transactions",
        "Fraud Rate (%)",
        "Total Transaction Amount",
        "Average Transaction Amount",
        "Critical Alerts",
        "High Risk Transactions",
        "Investigation Required",
        "Review Required"

    ],

    "Value": [

        total_transactions,
        total_frauds,
        round(fraud_rate,4),
        round(total_amount,2),
        round(avg_amount,2),
        critical_alerts,
        high_risk,
        investigation_required,
        review_required

    ]

})

executive_kpis

                          KPI         Value
0          Total Transactions  6.362620e+06
1          Fraud Transactions  8.213000e+03
2              Fraud Rate (%)  1.291000e-01
3    Total Transaction Amount  1.144393e+12
4  Average Transaction Amount  1.798619e+05
5             Critical Alerts  7.352000e+03
6      High Risk Transactions  7.320000e+02
7      Investigation Required  8.084000e+03
8             Review Required  8.193000e+03

In [71]:
executive_kpis.to_csv(
    "../data/processed/executive_kpis.csv",
    index=False
)

print("Executive KPI Dataset Saved")

Executive KPI Dataset Saved

In [72]:
executive_kpis

                          KPI         Value
0          Total Transactions  6.362620e+06
1          Fraud Transactions  8.213000e+03
2              Fraud Rate (%)  1.291000e-01
3    Total Transaction Amount  1.144393e+12
4  Average Transaction Amount  1.798619e+05
5             Critical Alerts  7.352000e+03
6      High Risk Transactions  7.320000e+02
7      Investigation Required  8.084000e+03
8             Review Required  8.193000e+03

In [73]:
risk_summary = (

    df.groupby(
        "risk_category"
    )

    .agg(

        transaction_count = (
            "risk_category",
            "count"
        ),

        avg_risk_score = (
            "risk_score",
            "mean"
        ),

        total_amount = (
            "amount",
            "sum"
        )

    )

    .reset_index()

)

risk_summary

  risk_category  transaction_count  avg_risk_score  total_amount
0      Critical               7352       98.549139  1.169291e+10
1          High                732       83.269577  3.218763e+08
2           Low            6354427        0.440267  1.132347e+12
3        Medium                109       61.486789  3.141904e+07

In [74]:
risk_order = {

    "Low":1,
    "Medium":2,
    "High":3,
    "Critical":4

}

risk_summary["sort_order"] = (

    risk_summary["risk_category"]

    .map(risk_order)

)

risk_summary = (

    risk_summary

    .sort_values(
        "sort_order"
    )

)

risk_summary

  risk_category  transaction_count  avg_risk_score  total_amount  sort_order
2           Low            6354427        0.440267  1.132347e+12           1
3        Medium                109       61.486789  3.141904e+07           2
1          High                732       83.269577  3.218763e+08           3
0      Critical               7352       98.549139  1.169291e+10           4

In [75]:
risk_summary[
    "percentage"
] = (

    risk_summary[
        "transaction_count"
    ]

    /

    risk_summary[
        "transaction_count"
    ].sum()

    * 100

).round(4)

risk_summary

,risk_category,transaction_count,avg_risk_score,total_amount,sort_order,percentage
2,Low,6354427,0.440267,1.132347e+12,1,99.8712
3,Medium,109,61.486789,3.141904e+07,2,0.0017
1,High,732,83.269577,3.218763e+08,3,0.0115
0,Critical,7352,98.549139,1.169291e+10,4,0.1155

In [76]:
risk_summary["percentage"] = (
    risk_summary["percentage"]
    .round(2)
)

In [77]:
risk_summary.to_csv(
    "../data/processed/risk_summary.csv",
    index=False
)

print(
    "Risk Summary Saved Successfully"
)

Risk Summary Saved Successfully

In [78]:
risk_summary

,risk_category,transaction_count,avg_risk_score,total_amount,sort_order,percentage
2,Low,6354427,0.440267,1.132347e+12,1,99.87
3,Medium,109,61.486789,3.141904e+07,2,0.00
1,High,732,83.269577,3.218763e+08,3,0.01
0,Critical,7352,98.549139,1.169291e+10,4,0.12

In [84]:
severity_summary = (

    df.groupby(
        "fraud_severity"
    )

    .agg(

        transaction_count=(
            "fraud_severity",
            "count"
        ),

        avg_risk_score=(
            "risk_score",
            "mean"
        ),

        total_amount=(
            "amount",
            "sum"
        )

    )

    .reset_index()

)

severity_order = {

    "No Risk":1,
    "Minor":2,
    "Moderate":3,
    "Severe":4,
    "Extreme":5

}

severity_summary["sort_order"] = (
    severity_summary["fraud_severity"]
    .map(severity_order)
)

severity_summary = (
    severity_summary
    .sort_values("sort_order")
)

severity_summary["percentage"] = (

    severity_summary["transaction_count"]

    /

    severity_summary["transaction_count"].sum()

    * 100

).round(4)

severity_summary

,fraud_severity,transaction_count,avg_risk_score,total_amount,sort_order,percentage
3,No Risk,6354427,0.440267,1.132347e+12,1,99.8712
1,Minor,33,51.755455,5.302915e+06,2,0.0005
2,Moderate,282,73.494929,1.149554e+08,3,0.0044
4,Severe,1248,90.013550,7.112112e+08,4,0.0196
0,Extreme,6630,99.158107,1.121473e+10,5,0.1042

In [85]:
severity_summary.to_csv(
    "../data/processed/severity_summary.csv",
    index=False
)

print(
    "Severity Summary Saved Successfully"
)

Severity Summary Saved Successfully

In [86]:
severity_summary

,fraud_severity,transaction_count,avg_risk_score,total_amount,sort_order,percentage
3,No Risk,6354427,0.440267,1.132347e+12,1,99.8712
1,Minor,33,51.755455,5.302915e+06,2,0.0005
2,Moderate,282,73.494929,1.149554e+08,3,0.0044
4,Severe,1248,90.013550,7.112112e+08,4,0.0196
0,Extreme,6630,99.158107,1.121473e+10,5,0.1042

In [87]:
regional_summary = (

    df.groupby(
        "risk_region"
    )

    .agg(

        total_transactions=(
            "risk_region",
            "count"
        ),

        fraud_transactions=(
            "isFraud",
            "sum"
        ),

        avg_risk_score=(
            "risk_score",
            "mean"
        ),

        total_amount=(
            "amount",
            "sum"
        )

    )

    .reset_index()

)

regional_summary

,risk_region,total_transactions,fraud_transactions,avg_risk_score,total_amount
0,Central,1272675,1664,0.562433,2.282602e+11
1,East,1272037,1597,0.556362,2.291810e+11
2,North,1272748,1668,0.567419,2.290910e+11
3,South,1271856,1596,0.571093,2.279055e+11
4,West,1273304,1688,0.563726,2.299553e+11

In [88]:
regional_summary["fraud_rate"] = (

    regional_summary["fraud_transactions"]

    /

    regional_summary["total_transactions"]

    * 100

).round(4)

In [89]:
regional_summary = (

    regional_summary

    .sort_values(
        "fraud_rate",
        ascending=False
    )

)

In [90]:
regional_summary.to_csv(
    "../data/processed/regional_summary.csv",
    index=False
)

print("Regional Summary Saved")

Regional Summary Saved

In [91]:
regional_summary

,risk_region,total_transactions,fraud_transactions,avg_risk_score,total_amount,fraud_rate
4,West,1273304,1688,0.563726,2.299553e+11,0.1326
2,North,1272748,1668,0.567419,2.290910e+11,0.1311
0,Central,1272675,1664,0.562433,2.282602e+11,0.1307
1,East,1272037,1597,0.556362,2.291810e+11,0.1255
3,South,1271856,1596,0.571093,2.279055e+11,0.1255

In [92]:
customer_summary = (

    df.groupby(
        "customer_segment"
    )

    .agg(

        total_transactions=(
            "customer_segment",
            "count"
        ),

        fraud_transactions=(
            "isFraud",
            "sum"
        ),

        avg_risk_score=(
            "risk_score",
            "mean"
        ),

        avg_transaction_amount=(
            "amount",
            "mean"
        )

    )

    .reset_index()

)

customer_summary

,customer_segment,total_transactions,fraud_transactions,avg_risk_score,avg_transaction_amount
0,Business,635993,816,0.528175,180140.773184
1,Premium,1273058,1637,0.558300,179749.085845
2,Retail,4453569,5760,0.571040,179854.328578

In [93]:
customer_summary["fraud_rate"] = (

    customer_summary["fraud_transactions"]

    /

    customer_summary["total_transactions"]

    * 100

).round(4)

In [94]:
customer_summary = (

    customer_summary

    .sort_values(
        "fraud_rate",
        ascending=False
    )

)

customer_summary

,customer_segment,total_transactions,fraud_transactions,avg_risk_score,avg_transaction_amount,fraud_rate
2,Retail,4453569,5760,0.571040,179854.328578,0.1293
1,Premium,1273058,1637,0.558300,179749.085845,0.1286
0,Business,635993,816,0.528175,180140.773184,0.1283

In [95]:
customer_summary.to_csv(
    "../data/processed/customer_summary.csv",
    index=False
)

print("Customer Summary Saved")

Customer Summary Saved

In [96]:
customer_summary

,customer_segment,total_transactions,fraud_transactions,avg_risk_score,avg_transaction_amount,fraud_rate
2,Retail,4453569,5760,0.571040,179854.328578,0.1293
1,Premium,1273058,1637,0.558300,179749.085845,0.1286
0,Business,635993,816,0.528175,180140.773184,0.1283

In [97]:
channel_summary = (

    df.groupby(
        ["channel"]
    )

    .agg(

        total_transactions=(
            "channel",
            "count"
        ),

        fraud_transactions=(
            "isFraud",
            "sum"
        ),

        avg_risk_score=(
            "risk_score",
            "mean"
        ),

        total_amount=(
            "amount",
            "sum"
        )

    )

    .reset_index()

)

channel_summary["fraud_rate"] = (

    channel_summary["fraud_transactions"]

    /

    channel_summary["total_transactions"]

    * 100

).round(4)

channel_summary = channel_summary.sort_values(
    "fraud_rate",
    ascending=False
)

channel_summary

,channel,total_transactions,fraud_transactions,avg_risk_score,total_amount,fraud_rate
0,ATM,954654,1272,0.569732,1.730282e+11,0.1332
3,Mobile App,3179608,4091,0.558680,5.713433e+11,0.1287
1,Branch,636334,814,0.572995,1.140293e+11,0.1279
2,Internet Banking,1592024,2036,0.568417,2.859923e+11,0.1279

In [98]:
channel_summary.to_csv(
    "../data/processed/channel_summary.csv",
    index=False
)

In [100]:
device_summary = (

    df.groupby(
        "device_type"
    )

    .agg(

        total_transactions=(
            "device_type",
            "count"
        ),

        fraud_transactions=(
            "isFraud",
            "sum"
        ),

        avg_risk_score=(
            "risk_score",
            "mean"
        )

    )

    .reset_index()

)

device_summary["fraud_rate"] = (

    device_summary["fraud_transactions"]

    /

    device_summary["total_transactions"]

    * 100

).round(4)

device_summary

,device_type,total_transactions,fraud_transactions,avg_risk_score,fraud_rate
0,Android,2861352,3700,0.559627,0.1293
1,Desktop,1273214,1692,0.566836,0.1329
2,Tablet,636967,791,0.564864,0.1242
3,iPhone,1591087,2030,0.570075,0.1276

In [101]:
device_summary.to_csv(
    "../data/processed/device_summary.csv",
    index=False
)

In [102]:
age_summary = (

    df.groupby(
        "age_group"
    )

    .agg(

        total_transactions=(
            "age_group",
            "count"
        ),

        fraud_transactions=(
            "isFraud",
            "sum"
        ),

        avg_risk_score=(
            "risk_score",
            "mean"
        )

    )

    .reset_index()

)

age_summary["fraud_rate"] = (

    age_summary["fraud_transactions"]

    /

    age_summary["total_transactions"]

    * 100

).round(4)

age_summary

,age_group,total_transactions,fraud_transactions,avg_risk_score,fraud_rate
0,18-25,1272479,1705,0.576579,0.1340
1,26-35,2226557,2763,0.560760,0.1241
2,36-45,1591818,2097,0.563255,0.1317
3,46-60,953551,1222,0.562529,0.1282
4,60+,318215,426,0.548633,0.1339

In [103]:
age_summary.to_csv(
    "../data/processed/age_summary.csv",
    index=False
)

In [105]:
model_performance = pd.DataFrame({

    "Model":[
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],

    "Accuracy":[
        0.964545,
        0.99999,
        0.99989
    ],

    "Precision":[
        0.032050,
        1.0,
        0.972
    ],

    "Recall":[
        0.906977,
        0.992248,
        0.941860
    ],

    "F1_Score":[
        0.061913,
        0.996109,
        0.956693
    ],

    "ROC_AUC":[
        0.982143,
        0.998650,
        0.999357
    ]

})

model_performance

                 Model  Accuracy  Precision    Recall  F1_Score   ROC_AUC
0  Logistic Regression  0.964545    0.03205  0.906977  0.061913  0.982143
1        Random Forest  0.999990    1.00000  0.992248  0.996109  0.998650
2              XGBoost  0.999890    0.97200  0.941860  0.956693  0.999357

In [106]:
model_performance.to_csv(
    "../data/processed/model_performance.csv",
    index=False
)

In [107]:
powerbi_master = df.copy()

In [108]:
powerbi_master = powerbi_master[

[
    "step",
    "type",
    "amount",

    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest",

    "isFraud",
    "fraud_probability",
    "risk_score",
    "risk_category",
    "fraud_severity",

    "transaction_hour",
    "transaction_day",
    "transaction_week",

    "customer_segment",
    "age_group",

    "channel",
    "device_type",

    "risk_region",

    "account_tenure_months",

    "alert_priority",
    "recommended_action"
]

]

In [109]:
print(powerbi_master.shape)

powerbi_master.head()

(6362620, 23)

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,fraud_probability,risk_score,...,transaction_day,transaction_week,customer_segment,age_group,channel,device_type,risk_region,account_tenure_months,alert_priority,recommended_action
0,1,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0,0.000000,0.00,...,1,1,Retail,26-35,Mobile App,iPhone,Central,20,Normal,Approve Transaction
1,1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0,0.000000,0.00,...,1,1,Retail,60+,Internet Banking,Android,East,7,Normal,Approve Transaction
2,1,TRANSFER,181.00,181.0,0.00,0.0,0.0,1,0.729989,73.00,...,1,1,Retail,36-45,Internet Banking,Desktop,East,39,Urgent,Require Multi-Factor Verification
3,1,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1,0.589770,58.98,...,1,1,Premium,36-45,Mobile App,Android,North,116,Review,Manual Review Recommended
4,1,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0,0.000000,0.00,...,1,1,Retail,18-25,Internet Banking,iPhone,East,19,Normal,Approve Transaction

In [110]:
powerbi_master.to_csv(
    "../data/processed/powerbi_master_dataset.csv",
    index=False
)

print("Power BI Master Dataset Saved")

Power BI Master Dataset Saved

# Power BI Dataset Generation Summary

Generated Files:

1. executive_kpis.csv
2. risk_summary.csv
3. severity_summary.csv
4. regional_summary.csv
5. customer_summary.csv
6. channel_summary.csv
7. device_summary.csv
8. age_summary.csv
9. model_performance.csv
10. powerbi_master_dataset.csv

Purpose:
These datasets support enterprise fraud analytics dashboards and executive reporting.